#!/bin/bash

#SBATCH -N 1                # 1 node
#SBATCH --ntasks-per-node=128 # 8 tasks out of 128
#SBATCH --time=00:50:00
#SBATCH --gres=gpu:4        # 1 gpus per node out of 4
#SBATCH -A FUAC6_UKAEA_ML
#SBATCH --constraint=gpureport
#SBATCH -p m100_fua_prod
# #SBATCH -p m100_all_serial

module purge
module load profile/base      
module load profile/deeplrn
module load cuda/10.1
module load gnu/8.4.0
module load python/3.8.2
module load cudnn/7.6.5--cuda--10.1
module load nccl/2.7.8--cuda--10.1
module load openblas/0.3.9--gnu--8.4.0
module load szip/2.1.1--gnu--8.4.0
module load zlib/1.2.11--gnu--8.4.0
module load hdf5/1.10.6--gnu--8.4.0       
module load tensorflow/2.3.0--cuda--10.1  

source /m100_work/FUAC6_UKAEA_ML/spamela/MAST_fast_camera/venv/bin/activate

./classify_images.py > nohup_file


